# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewsFeed' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'JGProgressHUD'
  pod 'Kingfisher'

  # Pods for NewsFeed

  target 'NewsFeedTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
